### PR TITLE
Add partners page

### PR DESCRIPTION
**Pull request by DanKhoo**
In this PR:
- Add partners API
- Add partners page

### CODE REVIEW

**Review by jamessspanggg — APPROVED** [review]
LGTM, are we intending to store all npoPartners locally in the project?

**Comment by kohchihao** [comment]
@jamessspanggg we can keep it locally. A bit no point to store it in firestore. Waste the reads hahaha

**Comment by jamessspanggg** [comment]
> @jamessspanggg we can keep it locally. A bit no point to store it in firestore. Waste the reads hahaha

i see noted

**Review by kohchihao — APPROVED** [review]
LGTM 👍

**Pull request merged**
