### PR TITLE
Add how it works section in home page

### PR DESCRIPTION
**Pull request by jamessspanggg**
Note: the marketing team also design these two images, not sure can be of use here.

mobile_donor_how_it_works_steps
mobile_npo_how_it_works_steps

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Awaiting designs for the how it works banner image and the images for each step

**Review by jinyingtan — COMMENTED** [review]
[Mobile] After clicking on `Done` of the slideshow: 
- when the slide show is open again, the bottom left button shows `Done` instead of next
- when the slide show is open again, the bottom drawer is on an empty slide

Screenshot 2020-12-15 at 5 39 04 PM
Screenshot 2020-12-15 at 5 42 35 PM

**Comment by jamessspanggg** [comment]
> [Mobile] After clicking on `Done` of the slideshow:
> 
> * when the slide show is open again, the bottom left button shows `Done` instead of next
> * when the slide show is open again, the bottom drawer is on an empty slide
> 
> Screenshot 2020-12-15 at 5 39 04 PM
> Screenshot 2020-12-15 at 5 42 35 PM

Fixed

**Review by kohchihao — APPROVED** [review]
LGTM 👍

**Pull request merged**
